services:
  web:
    restart: always
    build: .
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    links:
      - db:mysql
    depends_on:
      - db
    environment:
      - APP_ENV=local  # production
      - APP_DEBUG=true # false
    networks:
      - backend

  db:
    restart: always
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - dbdata:/var/lib/mysql

    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  dbdata:
